import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Cursor from '@/src/components/Cursor';
import './globals.css';

const inter = Inter({
     variable: '--font-inter',
     subsets: ['latin'],
});

export const metadata: Metadata = {
     title: 'Create Next App',
     description: 'Generated by create next app',
};

export default function RootLayout({
     children,
}: Readonly<{
     children: React.ReactNode;
}>) {
     return (
          <html lang="pt-br" className={`${inter.variable} h-full antialiased`}>
               <body className="min-h-full flex flex-col relative isolate overflow-x-hidden cursor-default">
                    <Cursor />
                    <div className="noise" aria-hidden="true" />
                    <div className="relative z-10">{children}</div>
               </body>
          </html>
     );
}
